### PR TITLE
Add Class sniffs

### PR DESCRIPTION
**Pull request by joshdavis11**
- Require the mustache on the same line like we do with other inline control structures (if, while, for, etc.)
- Require one space after the class declaration before the mustache like we do with other inline control structures (if, while, for, etc.)
- [x] Jeanette Approval
- [ ] John Approval
- [x] Jon Approval

### CODE REVIEW

**Comment by jeanettemartin** [comment]
yay yay yay yay!

**Comment by jeanettemartin** [comment]
Do you know if all the files in BambooHR will pass this test or if there's going to be cleanup to do?

**Comment by joshdavis11** [comment]
There will be some cleanup. Here's the results from running the summary report:

```
PHP CODE SNIFFER REPORT SUMMARY
----------------------------------------------------------------------
FILE                                                  ERRORS  WARNINGS
----------------------------------------------------------------------
...BambooHR/Command/Field/FieldEncryptionCommand.php  2       0
...on/Exceptions/CompanyMasterNotLoadedException.php  1       0
...p/BambooHR/Common/Exceptions/OfflineException.php  1       0
...ambooHR/Controller/Benefit/BulkEditController.php  2       0
...er/Benefit/Report/BenefitReportAjaxController.php  2       0
...roller/Employees/EmployeeTab/RehireController.php  1       0
...ler/Payroll/PayrollChangeReportAjaxController.php  2       0
.../main/app/BambooHR/Domain/AlertDispatchDomain.php  2       0
...ooHR/Domain/TimeOffDomain/AccrualEngineDomain.php  2       0
...eOffDomain/AccrualTypes/SemiAnnualAccrualType.php  1       0
...p/BambooHR/Domain/TimeOffDomain/TimeOffDomain.php  1       0
...main/app/BambooHR/Files/Client/BaseFileClient.php  2       0
.../repos/main/app/BambooHR/Filter/FilterContext.php  1       0
...repos/main/app/BambooHR/Logging/RollbarLogger.php  2       0
...BambooHR/Model/Billing/BillingProviderFactory.php  2       0
...mbooHR/Model/Billing/BillingProviderInterface.php  2       0
...odel/Billing/Internal/InternalBillingProvider.php  2       0
...el/Billing/Internal/InternalSubscriberAccount.php  2       0
...ooHR/Model/Billing/SubscriberAccountInterface.php  2       0
...el/Billing/SubscriberAccountProviderInterface.php  2       0
...odel/Employee/Updater/ApprovalWorkflowUpdater.php  2       0
...Model/Employee/Updater/CompoundInstantUpdater.php  2       0
...odel/Employee/Updater/CompoundWorkflowUpdater.php  2       0
.../BambooHR/Model/Employee/Updater/TableUpdater.php  2       0
...p/BambooHR/Model/EmployeeDirectDepositAccount.php  2       0
.../Model/Subscription/SubscriptionFullInterface.php  1       0
...QuickForm2/DataSources/DefaultValueDataSource.php  2       0
...s/main/app/BambooHR/QuickForm2/Elements/Label.php  1       0
...kForm2/Fields/Checkbox/PrimaryContactCheckbox.php  2       0
...HR/QuickForm2/Fields/Text/ContactAddressLine1.php  2       0
...HR/QuickForm2/Fields/Text/CurrencyChangeField.php  2       0
...in/app/BambooHR/QuickForm2/Forms/ContactsForm.php  2       0
...ain/app/BambooHR/QuickForm2/Groups/PhoneGroup.php  1       0
...in/app/BambooHR/QuickForm2/Interfaces/Element.php  2       0
.../app/BambooHR/QuickForm2/Interfaces/UpdateRow.php  2       0
.../QuickForm2/Tables/CompensationHistoryElement.php  1       0
...pos/main/app/BambooHR/QuickForm2/Xml/Comparer.php  2       0
...in/app/BambooHR/QuickForm2/Xml/ComparerReader.php  2       0
...s/main/app/BambooHR/Reports/ReportMenuOptions.php  2       0
...pp/BambooHR/Repository/ApiLocaleConfiguration.php  2       0
...app/BambooHR/Repository/Audit/AuditRepository.php  2       0
...HR/Repository/CustomFieldEncryptionRepository.php  2       0
...BambooHR/Repository/Payroll/PayrollRepository.php  2       0
...pp/BambooHR/Service/AlertService/AlertRequest.php  1       0
...ployeeTab/DataObject/EmployeeStatusDataObject.php  1       0
...oHR/Silo/EmployeeTab/RehireProcessTransaction.php  1       0
.../Silo/EmployeeTab/Repository/RehireRepository.php  1       0
...app/BambooHR/Utility/Auth/Remote/ZendeskTools.php  2       0
...repos/main/app/BambooHR/Utility/DateImmutable.php  2       0
...oHR/Utility/Greenhouse/StatusUpdaterInterface.php  1       0
...repos/main/app/BambooHR/Utility/Toggle/Toggle.php  2       0
----------------------------------------------------------------------
A TOTAL OF 87 ERRORS AND 0 WARNINGS WERE FOUND IN 51 FILES
----------------------------------------------------------------------
```

**Comment by joshdavis11** [comment]
Also, there should be a way to setup the beautifier to easily fix these, but I hadn't gotten that deep into the sniff. I think I'd like to add that before we release this sniff so it's an easy cleanup job.

**Comment by jeanettemartin** [comment]
I just don't want this sniff to break all the branches so we can't pass phpcs

**Comment by joshdavis11** [comment]
Oh definitely. We have releases here and in our main repo we use those releases so even if I deployed the change over here, our main repo wouldn't pick it up until the `composer.json` file was updated.

**Comment by joshdavis11** [comment]
@jeanettemartin https://github.com/BambooHR/phpcs/pull/15/commits/21d6814ef99c4262126889fc0c0f6e57ca33d249 and https://github.com/BambooHR/phpcs/pull/15/commits/fd2fb09af14af384b0261e9f939dc529d816b17a -- beautifier. Ran it locally and it fixed all the things.

**Comment by jongardiner** [comment]
Looks good.  You'll want to help everybody out by doing a PR on the app code that does nothing but deploy the beautified results.  The diff should be trivial to review for correctness and it won't require testing.

**Comment by joshdavis11** [comment]
I was in the process of doing that before lunch. Just finished and here's the PR: https://github.com/BambooHR/main/pull/9869

**Pull request merged**
