### PR TITLE
Don't flag concat operator issues on newlines

### PR DESCRIPTION
**Pull request by joshdavis11**
Newlines are a pain to deal with. Currently if the end of a line is a concatenation operator, PHPCS will flag it as invalid. We should allow it as long is it the last thing on a line.

@cdburgess, @m2bright, and @jlesueur what do you think about making this change?

### CODE REVIEW

**Comment by jlesueur** [comment]
BTW, if we are writing SQL, I prefer putting it in a multi-line string:

$sql = "
    SELECT
         *
    FROM table
        JOIN table2 ON
            table.id = table2.table_id
    WHERE
        table2.status = 'active'";
rather than using concatenation. It is much easier to work with. The only reason to do concatenation for long strings is if those newlines will actually interfere with things.

**Comment by joshdavis11** [comment]
Agreed. There is a particular case I'm working on where I need the concat operator, though. This change would accommodate that and I really don't think we should flag the concat operator if its at the end of a line.

My example is this:
```php
return 'users.id AS id,' . PHP_EOL .
	'users.company_id AS companyId,' . PHP_EOL .
	'users.username AS username,' . PHP_EOL .
	'users.hash_password AS hashPassword,' . PHP_EOL .
	'users.first_name AS firstName,' . PHP_EOL .
	'users.last_name AS lastName,' . PHP_EOL .
	'users.email AS email,' . PHP_EOL .
	'users.employee_id AS employeeId,' . PHP_EOL .
	'users.last_login AS lastLogin,' . PHP_EOL .
	'users.status AS status,' . PHP_EOL .
	'users.type AS type,' . PHP_EOL .
	'users.portal_user_id AS portalUserId,' . PHP_EOL .
	'users.language_id AS languageId,' . PHP_EOL .
	'users.support_admin AS supportAdmin,' . PHP_EOL .
	'users.key_contact AS keyContact,' . PHP_EOL ;
```
I need to match the string exactly with the new lines and spacing.

**Comment by jlesueur** [comment]
I'm fine with the change. I'm just a curmudgeon who likes to derail things with my complaining.

**Comment by m2bright** [comment]
I agree. I am ok with this as well.

**Comment by cdburgess** [comment]
Not sure how I feel about this. I think I am ok with it if there are no other side affects.

**Comment by joshdavis11** [comment]
I think it's fairly self-contained. Our only requirement is spaces around the concat operator and this will allow that to still be sniffed.

**Comment by joshdavis11** [comment]
Also, it looks like CIHUB isn't flagging this anyway. I pushed my changes up in a PR (https://github.com/BambooHR/main/pull/8971/files#diff-d0a57cc477942d7033b62626f911ee38R34) and everything passed. I don't why it did, but it shouldn't...

**Pull request merged**
